name: reusable-pr-flow

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      build_command:
        required: true
        type: string
      itest_command:
        required: false
        type: string
      test_results_files:
        required: true
        type: string
      spotbugs_results_files:
        required: false
        type: string
      slack_channel_id:
        required: false
        type: string

    secrets:
      aws_ca_domain:
        description: 'AWS_CA_DOMAIN'
        required: false
      aws_ca_owner_id:
        description: 'AWS_CA_OWNER_ID'
        required: false
      aws_role_to_assume:
        description: 'AWS_ROLE_TO_ASSUME'
        required: false
      slack_webhook_url:
        description: 'SLACK_WEBHOOK_URL'
        required: false
      slack_channel_id:
        required: false
      sonar_token:
        description: 'SONAR_TOKEN'
        required: false
      sonar_host_url:
        description: 'SONAR_HOST_URL'
        required: false


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  start-pr-build:
    name: Start pull-request build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.aws_role_to_assume }}
          aws-region: eu-central-1

      - name: Initialize variables
        id: vars
        run: |
          echo "::set-output name=run_url::https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ inputs.build_command }}

      - name: Publish spotbugs results
        uses: jwgmeligmeyling/spotbugs-github-action@master
        if: ${{ failure() && inputs.spotbugs_results_files != 0 }}
        with:
          path: ${{ inputs.spotbugs_results_files }}

      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.sonar_token }}
          SONAR_HOST_URL: ${{ secrets.sonar_host_url }}

      - name: Run integration tests
        uses: gradle/gradle-build-action@v2
        if: ${{ inputs.itest_command != 0 }}
        with:
          arguments: ${{ inputs.itest_command }}

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ${{ inputs.test_results_files }}

      - name: Post to Slack channel
        if: ${{ failure() }}
        id: slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
        uses: slackapi/slack-github-action@v1.18.0
        with: 
          payload: |
            {
              "status": "Build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "author": "Pull request author: ${{ github.event.pull_request.user.login }}"
            }